### PR TITLE
spatilise_im.py lost arg.component during recent merge

### PR DESCRIPTION
**Pull request by sungeunbae**

### CODE REVIEW

**Review by jasonmotha — APPROVED** [review]

**Comment by jasonmotha** [comment]
I assume it's been tested?

**Comment by jasonmotha** [comment]
@joelridden I think this may be helpful for you?

**Review by jpa198 — CHANGES_REQUESTED** [review]
It only gets used as a global, this should be changed to being passed as an argument

**Comment by sungeunbae** [comment]
> I assume it's been tested?

yep, tested

**Review by jpa198 — APPROVED** [review]

**Comment by jasonmotha** [comment]
@sungeunbae For future bug-checking; how did you test this? There was a pretty major flaw.

**Comment by sungeunbae** [comment]
> @sungeunbae For future bug-checking; how did you test this? There was a pretty major flaw.

You mean "test after my fix" or "test to discover this bug"?

**Comment by joelridden** [comment]
> @joelridden I think this may be helpful for you?

Yea I just set it manually when I needed it, probably should have mentioned it before.

**Pull request merged**
